const BUSAN_FOOD_SERVICE_API =
  "http://apis.data.go.kr/6260000/FoodService/getFoodKr";

const BUSAN_FOOD_SERVICE_API_EN =
  "http://apis.data.go.kr/6260000/FoodService/getFoodEn";

const BUSAN_FOOD_SERVICE_ENCODING_KEY =
  "OcicxwQmjw1fh9B5gPALdX%2BW3JAa3iqWkJm2UuQ%2BccCshV%2FTJEicTsrXJNTWOkRIYgStjJf%2BBuHMsIqJNXYouw%3D%3D";

const BUSAN_FOOD_SERVICE_DECODING_KEY =
  "OcicxwQmjw1fh9B5gPALdX+W3JAa3iqWkJm2UuQ+ccCshV/TJEicTsrXJNTWOkRIYgStjJf+BuHMsIqJNXYouw==";

export default {
  BUSAN_FOOD_SERVICE_API,
  BUSAN_FOOD_SERVICE_API_EN,
  BUSAN_FOOD_SERVICE_DECODING_KEY,
  BUSAN_FOOD_SERVICE_ENCODING_KEY,
} as const;
